server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/omechu
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 628475285967-1mufurlb0u8fg4m1eas0b1922o3m5fjv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 794888801796699
            client-secret: 4280867a5fe568947e0fe790c7783db7
            scope:
              - email
              - public_profile

          naver:
            client-id: iFbAGXM7b8VpVRa3UE4G
            client-secret: tvJDJ5BPZx
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌.
